=head1 NAME

millidea - Ideas for Mill that still have to be refined

=head1 DESCRIPTION

=over

=item C<else> on C<for> and C<while> loops in case they didn't run at least
once.

=item Multiple variable declarations at once for parameters and C<let>
bindings. For example:

    proc f(x $y: String) {
        check x == $y
        $y += 1
        check x != $y
    }

    let x $y = 1
    check x == $y
    $y += 1
    check x != $y

=cut
