=head1 NAME

milldata - Mill types and values

=head1 DESCRIPTION

Mill has a dynamic type system.

=head2 Types

=head3 The Top and Bottom Types

The top type is a supertype of all types. The bottom type is a subtype of all
types. There are no types that are strict supertypes of the top type and there
are no types that are strict subtypes of the bottom type. There are no values
of the bottom type.

The bottom type is typically used as the return type for subroutines that never
return, and as the exception specification for subroutines that never throw.

=head3 Protocol Types

A protocol type defines a set of subroutines which can be overloaded by a
protocol implementation. A protocol implementation overloads these subroutines
for some type, making that type a subtype of the protocol type.

    protocol Monitor {
        proc start(monitor: this) ensure !stopped(monitor)
        proc stop(monitor: this) ensure stopped(monitor)
        func running(monitor: this): Boolean
    }

    struct PingMonitor {
        address: Address
        interval: Duration
    }

    implement Monitor for PingMonitor {
        proc start(monitor: PingMonitor) { ... }
        proc stop(monitor: PingMonitor) { ... }
        proc running(monitor: PingMonitor) { ... }
    }

=head3 Structure Types

A structure type defines a set of fields.

    struct User {
        id: Int
        name: String
        birthday: LocalDate
    }

A lens will be generated for each field.

=head3 Union Types

A union type represents one of many possible structures.

    union Option {
        Some(x: Any)
        None
    }

Optionally, a union type can describe fields common to all variants:

    union Token {
        common(position: Int)
        Identifier(name: String)
        StringLiteral(value: String)
        EOF
    }

The common fields will be inserted at the beginning of the field list for every
variant.

A lens will be generated for each common field. A prism will be generated for
each non-common field.

=head2 Destruction

When the reference count of a Mill value reaches zero, the C<destruct>
procedure in the C<mill> module is invoked if it is overloaded for the type of
the value. The value is passed as the argument to C<destruct>.

=cut
